### ISSUE TITLE
Error importing module

### ISSUE THREAD

**Issue by barryross** [flivni/ionic2-autosize#1]
I am still getting familiar with ionic2 and Angular2.  Does this seem like an issue with the package itself or can you please let me know if I am loading this improperly?  

I have done the following

1) `npm install ionic2-autosize --save`

2) My `declarations.d.ts` file has `declare module '*';`

3) In `app.module.ts`, I have `import { Autosize } from 'ionic2-autosize';`

and 
`@NgModule({
  declarations: [
		Autosize
  ],`

I am receiving this message:
<img width="958" alt="screen shot 2016-12-20 at 12 31 28 pm" src="https://cloud.githubusercontent.com/assets/2281667/21366821/545ea98a-c6b0-11e6-933a-ec8883333435.png">

**Comment by zmbc** [comment]
The Ionic 2 ecosystem has been constantly in flux. When this module was created, Gulp was the build tool (it's since become vanilla Node scripts) and Browserify was used for bundling (replaced by Rollup, which was then replaced by Webpack).

The issue you're having is that the Typescript files within `ionic2-autosize` are not being transpiled into Javascript. In the old build system, we found a way to transpile them along with the rest of the source files. When `ionic-app-scripts` came out, a lot changed and we ended up just including the source of this module via copy-and-paste instead of npm. You could do that by copying the `autosize.directive.ts` file into your `src` folder somewhere.

If you find a way to tell `ionic-app-scripts` to transpile the contents of `node_modules/ionic2-autosize`, let us know and we can put it in the README.

**Comment by barryross** [comment]
Thank you for the in-depth response...I really appreciate it!

**Comment by flivni** [comment]
Hi @barryross - We've updated the module. It should work now.
