### ISSUE TITLE
Error in using ionc2-autosize

### ISSUE THREAD

**Issue by praveens96** [flivni/ionic2-autosize#2]
i am trying to consume this in my project to autoresize my ion-buttons based on the text coming from service dynamically.
when i installed and imported it in my app.modules.ts, its returning me the below error.
<img width="437" alt="screen shot 2017-03-13 at 11 27 01 am" src="https://cloud.githubusercontent.com/assets/8864727/23843219/3be67ed4-07e0-11e7-8d3a-a9290ef91f44.png">

**Error Message:** Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open '/Users/e571224/Desktop/praveen/UnifiedEventApp/unified-event-app/node_modules/ionic2-autosize/index.js'

angular2-autosize is also giving the same issue. any idea on how to use it?

**Comment by flivni** [comment]
Hi @praveens96 . I'm sorry. I don't have time to take a look at this right now :(.

**Comment by vipinvijay** [comment]
I am also facing the same issue. Kindly suggest

**Comment by stefan-beyer** [comment]
I just had the same issue and I read that it has something to do with different versions of whatever ;) (sorry I'm an Ionic newbie)
The "quick solution" was, to put `node_modules/ionic2-autosize/src/autosize.directive.ts` somewhere in the projects `src` folder - so that it will be compiled - and import it from there.

**Comment by flivni** [comment]
Hi @praveens96 -- we've updated the module. This should work for you now.
